# Stage 1: Build & Bundle Angular SPA
FROM node:26-bookworm-slim@sha256:cd565714d4da3e84bfd341e31448f81d47c6362198f152345297c9c1154e6341 AS builder

WORKDIR /app
ARG BUILD_ENV=development

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npx nx build client -c=${BUILD_ENV}

# Stage 2: Hardened Unprivileged Web Server
FROM nginxinc/nginx-unprivileged:alpine-slim@sha256:e70fd9f31a5b628a5d8b3063e87396b2d3641b1448f47d8eddafef3df3d103bd

# Copy assets and give ownership directly to the unprivileged nginx user
COPY --chown=nginx:nginx --from=builder /app/dist/apps/client/browser/ /usr/share/nginx/html/
COPY --chown=nginx:nginx nginx.conf /etc/nginx/conf.d/default.conf

# Copy the script, grant execute permissions, and assign ownership in one step!
COPY --chown=nginx:nginx --chmod=755 apps/client/inject-env.sh /docker-entrypoint.d/40-inject-env.sh

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]