# Stage 1: Build & Bundle Angular SPA
FROM node:26-bookworm-slim AS builder

WORKDIR /app
ARG BUILD_ENV=development

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npx nx build client -c=${BUILD_ENV}

# Stage 2: Hardened Unprivileged Web Server
FROM nginxinc/nginx-unprivileged:alpine-slim

# Copy assets and give ownership directly to the unprivileged nginx user
COPY --chown=nginx:nginx --from=builder /app/dist/apps/client/browser/ /usr/share/nginx/html/
COPY --chown=nginx:nginx nginx.conf /etc/nginx/conf.d/default.conf

# Copy the script, grant execute permissions, and assign ownership in one step!
COPY --chown=nginx:nginx --chmod=755 apps/client/inject-env.sh /docker-entrypoint.d/40-inject-env.sh

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]