services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: signingroom-worker
    command: ['serve', 'worker.capnp', '--verbose']
    ports:
      - '8787:8787'
    environment:
      - ALLOWED_ORIGIN=http://localhost:4200
      - API_PUBLIC_URL=http://localhost:8787
      - ENVIRONMENT=development

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        BUILD_ENV: development
    container_name: signingroom-client
    ports:
      - '4200:8080'
    depends_on:
      - worker
